CREATE TABLE IF NOT EXISTS candidates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(50),
  city VARCHAR(100),
  state VARCHAR(100),
  preferred_titles TEXT[],
  job_types TEXT[],
  work_setting TEXT CHECK (work_setting IN ('REMOTE','HYBRID','ONSITE','ANY')),
  salary_min INT,
  salary_max INT,
  years_experience INT,
  industries TEXT[],
  timeframe VARCHAR(100),
  linkedin_url TEXT,
  portfolio_url TEXT,
  skills TEXT[],
  certifications TEXT[],
  education TEXT,
  work_authorization VARCHAR(100),
  availability_date DATE,
  preferred_companies TEXT[],
  summary TEXT,
  resume_filename TEXT,
  resume_original_name TEXT,
  profile_image_filename TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
